services:
  admin-review:
    build:
      context: .
      dockerfile: apps/admin-review/Dockerfile
    environment:
      PORT: "4200"
      COMMUNITY_API_URL: "http://community-api:4000"
    ports:
      - "4200:4200"
    depends_on:
      - community-api

  community-api:
    build:
      context: .
      dockerfile: services/community-api/Dockerfile
    environment:
      PORT: "4000"
    ports:
      - "4000:4000"

  pet-generator:
    build:
      context: .
      dockerfile: services/pet-generator/Dockerfile
    environment:
      PORT: "4100"
    ports:
      - "4100:4100"
